### ISSUE TITLE
Consolidate imports at the top of the file

### ISSUE THREAD

**Issue by asolano** [matsuolab/transformer_tutorial#6]
The original imports of the notebook are all over the place. PEP8 and similar best practices recommend having all imports at the top of the file.

**Comment by yasu-k2** [comment]
I'll be working on this.

**Comment by asolano** [comment]
Please do!

**Comment by yasu-k2** [comment]
I've created a pull request! #8

**Comment by asolano** [comment]
Thanks, merged
